### ISSUE TITLE
1.16.2/0.3.0-alpha1.jar Critical injection failure

### ISSUE THREAD

**Issue by Katorone** [NathanPB/DeepMobLearning-Refabricated#22]
https://pastebin.com/cTC5b352

If I can be of more help, let me know.
Also on Discord: Katorone#2957

**Comment by NathanPB** [comment]
Thank you for reporting, this is fixed now. Its taking a bit longer, but should be available on curseforge in the next few minutes: https://www.curseforge.com/minecraft/mc-mods/deep-mob-learning-refabricated/files

**Comment by Katorone** [comment]
Thanks!  I'll test this version tomorrow. (I'm running an experimental server, but try to keep updates down to once a day)
