### ISSUE TITLE
Configure options

### ISSUE THREAD

**Issue by Osprey14** [NathanPB/DeepMobLearning-Refabricated#34]
I'll change a setting and it doesn't work, ill change the glitch armor to use half a data or 0 and it still uses 1.

**Comment by L0GGAN** [comment]
As far as i can tell none of the settings actually change anything. the glitch armor completely uses up a data module in a couple seconds just standing there

**Comment by NathanPB** [comment]
> I'll change a setting and it doesn't work, ill change the glitch armor to use half a data or 0 and it still uses 1.

There is no half data, so if you set float values it will **randomly** consume a full data point or consume nothing, based in a change of ``decimal_value``%. Eg. ``0.5`` has 50% of chance of consuming one data, ``10.5`` will consume 10 data and has 50% of chance of consuming 10 + 1 data.

**Comment by NathanPB** [comment]
> As far as i can tell none of the settings actually change anything. the glitch armor completely uses up a data module in a couple seconds just standing there

Kinda right. It does reduce the amount consumed, but depending on the effect that your armor has, it is completely possible to consume a data model in idle (not in a couple seconds lol. If so, please tell me the effect so I can rebalance it).

E.g. if you are wearing a Plenty armor (reduces hunger when in overworld sunlight), it will eventually drain the entire data model if you afk in a place that meet the required conditions
