### ISSUE TITLE
This is more of a question rather than a problem

### ISSUE THREAD

**Issue by WarMachine165** [NathanPB/DeepMobLearning-Refabricated#35]
does anyone know how to upgrade glitch armor once it's been crafted? I've been trying to find something on this but I can't find anything

**Comment by WarMachine165** [comment]
its at faulty tier right now but i just have no idea how to upgrade it

**Comment by NathanPB** [comment]
Just put it in the Matter Condenser along with pristine matters

**Comment by NathanPB** [comment]
If your question was not answered please reopen the issue =)
