### ISSUE TITLE
Glitch not spawing in multiplayer trial

### ISSUE THREAD

**Issue by NotAPotat0** [NathanPB/DeepMobLearning-Refabricated#36]
the glitch bar shows up on the top of the screen but nothing ever happens. I have one other player online and i also tried it while he was offline.

**Comment by NathanPB** [comment]
Which mod version are you running?

**Comment by NathanPB** [comment]
So sorry, I messed up.

Please update the mod to ``0.3.2-beta2`` and delete the file ``your_mc_installation/config/dml-refabricated.json``.

If you don't want to delete that file, just open it in a text editor and change the "warmupTime" to 60.
![image](https://user-images.githubusercontent.com/18128642/111232211-68512080-85c9-11eb-9284-b5db5535f35f.png)
