### ISSUE TITLE
Request; Glitch Armor Elytra

### ISSUE THREAD

**Issue by Chaogomu** [NathanPB/DeepMobLearning-Refabricated#41]
The idea here a slot in the Glitch Chestplate for an Elytra that either adds an Elytra to the chestplate or changes the flight mode granted by From Emeritus.

**Comment by NathanPB** [comment]
Thanks for your suggestion, but I will not be adding this for now in favor of the [Winged](https://www.curseforge.com/minecraft/mc-mods/winged/) mod. I think you might be interested in taking a look into it
