### ISSUE TITLE
Request; From Hades makes Glitch armor count as gold for piglins.

### ISSUE THREAD

**Issue by Chaogomu** [NathanPB/DeepMobLearning-Refabricated#42]
The idea is simple, Some level of From Hades makes piglins treat it as if it were slotted in a piece of gold armor.

This would be a handy little addition.

**Comment by NathanPB** [comment]
Thanks, this will be added whenever I get enough motivation to update to 1.17

**Comment by Luligabi1** [comment]
Hi! This suggestion has been implemented on the development branch as a Modular Effect. It's called `Piglin Truce` in-game and requires a Data Model Tier equal or higher to `Advanced`. Thank you again for the suggestion :)
