### ISSUE TITLE
Alpha 2 Report | Deep Learner GUI

### ISSUE THREAD

**Issue by KavisKryptic** [NathanPB/DeepMobLearning-Refabricated#47]
I was not sure about reporting this due to this still being in Alpha. But I'm just reporting it anyways just in case you weren't aware:

The GUI of the deep learner, the slots where you input [In comparison to the photo in the wiki] seemed skewed to right. There's also no model of the mob data selected, in addition it doesn't say the type of mob selected. Here are some example images 

 
![image](https://user-images.githubusercontent.com/51237952/121837840-7cb9bd80-cc8b-11eb-8c73-bb0bfe3a9fb0.png)
![image](https://user-images.githubusercontent.com/51237952/121837863-880ce900-cc8b-11eb-885e-208cde241bfd.png)
![image](https://user-images.githubusercontent.com/51237952/121837883-8e02ca00-cc8b-11eb-97e2-acdd405bb064.png)

Hope this helps!

**Comment by NathanPB** [comment]
I'm still working to port this GUI, will keep this open as a remainder

thanks
