### ISSUE TITLE
glitch armor is actual glitch armor

### ISSUE THREAD

**Issue by minecrafterseppe** [NathanPB/DeepMobLearning-Refabricated#52]
i bet u waited for a title like this

updated the modpack AOF4 from version 0.0.7  to 0.0.8 
its on a server aswell
and my armor now looks like this
![image](https://user-images.githubusercontent.com/13523046/127345681-8554b2b0-8da7-4e1f-9ca9-df3bd97d1001.png)

**Comment by NathanPB** [comment]
lmao I'm waking up for this
