### ISSUE TITLE
glitch armor makes you immortal

### ISSUE THREAD

**Issue by NeroOner** [NathanPB/DeepMobLearning-Refabricated#55]
ello! i'm playing all of fabric 3 on my own server, and i just got myself a set of glitch armor! thing is, it makes me unable to take damage. i have no idea as to why this is, i tested it in a singleplayer world and it works just fine

**Comment by NathanPB** [comment]
Been some time since this issue happened and I couldn't confirm it. Maybe it was a temporary conflict in the AoF pack, I assume that this is already fixed because no one else complained

I will be closing this for now, if the issue happen again please reopen :)
