### ISSUE TITLE
Parity with Simulacrum's GUI style

### ISSUE THREAD

**Issue by Luligabi1** [NathanPB/DeepMobLearning-Refabricated#68]
GUIs on base, modular-armor and upcoming modules should have style parity with [Simulacrum's Simulation Chamber GUI](https://github.com/NathanPB/DeepMobLearning-Refabricated/blob/develop/simulacrum/src/main/resources/assets/dmlsimulacrum/textures/gui/simulation_chamber_base.png) design. Not only is it prettier than vanilla's, it's also similar to the original DML's style.

Progress on development branch:

**`base` module:**
- [x] General Changes (textures, title color, etc.);
- [x] Deep Learner;
- [x] Loot Fabricator;

**`modular-armor` module:**
- [x] Modular Armor's module screen;
- [x] Matter Condenser;

**`rei-compat` module:**
~~General Changes (textures can't be reused from libgui!)~~
~~Soot redstone crafting~~
~~Loot Fabrication crafting~~
~~Trial Display~~
Turns out REI doesn't play nice with people trying to extend its widgets. If this changes on a future version, here's the [half-way done texture](https://imgur.com/JGNQ46P.png) I've done for this.

**Comment by NathanPB** [comment]
Do you think it would look better? I asked myself that same question when I started the mod and the answer was "no". However you can probably come with something way better then what I thought back then

Is it possible to restyle the libgui components? It would be great if so

**Comment by Luligabi1** [comment]
> Do you think it would look better? I asked myself that same question when I started the mod and the answer was "no". However you can probably come with something way better then what I thought back then


I don't plan on using the original mod's textures for this, so I'm not quite sure on how good it would look, but there's certainly room for improvement here.

> Is it possible to restyle the libgui components? It would be great if so

Yes, check what [Steven did for Wireless Networks for example](https://i.imgur.com/tXo5DWj.png)

**Comment by NathanPB** [comment]
I think we are well addressed then, it will add a lot to the mod's identity
