### ISSUE TITLE
java.io.UTFDataFormaException

### ISSUE THREAD

**Issue by Katorone** [NathanPB/DeepMobLearning-Refabricated#7]
When trying to connect to my test server I'm getting the following error:
![image](https://user-images.githubusercontent.com/918422/89105653-42548280-d423-11ea-858c-de3ac8418da0.png)

There are no crashes or other weird errors in the console or logs of both the client and server.

I'm using: 
- Fabric loader : 0.9.0-build.204
- Fabric API fabric-api-0.16.0+build.384-1.16.1.jar
- DML: deepmoblearning-refabricated-0.1.1-beta.jar
- Kotlin: fabric-language-kotlin-1.3.72+build.1.jar

This even happens when I remove all other mods but the three above from my test server.
If I can help by adding more logs, do let me know.

**Comment by NathanPB** [comment]
Thank you for reporting, fixed in 9eb46687cff307c5433da25921462b58557f1258. I'll be releasing a new version today with this along with some extra fixes

**Comment by Katorone** [comment]
Thank you!

**Comment by NathanPB** [comment]
Its out on curseforge: https://www.curseforge.com/minecraft/mc-mods/deep-mob-learning-refabricated/files/3020893

**Comment by Katorone** [comment]
I can confirm that this bug is fixed.  Thanks again!
