### ISSUE TITLE
Ghost Data Model resets to Faulty after long usage in chestplate

### ISSUE THREAD

**Issue by NoudZandbergen** [NathanPB/DeepMobLearning-Refabricated#80]
I don't know how to reproduce it, but it's happened twice now. If this is a feature and not a bug, players really should be warned in some way.

**Comment by NathanPB** [comment]
Were you flying with the armor?

**Comment by NoudZandbergen** [comment]
It didn't reset mid-flight, no. But I had been flying for quite some time using it.

**Comment by NathanPB** [comment]
Well then, the data model reset because data is consumed while you fly

**Comment by NoudZandbergen** [comment]
Ah well that'll do it haha. Have you considered adding any mechanisms that can make flight more sustainable?

**Comment by Luligabi1** [comment]
> Ah well that'll do it haha. Have you considered adding any mechanisms that can make flight more sustainable?

Not at the moment, what you can do is change the values used by flying.

1. Go to the `.minecraft/config directory`
2. Find `dml-refabricated.json` and open it
3. Change the `fly` value to what ever you think would be more fair. Default value is `0.05`

If any questions or issues arise, please open a new issue or contact us on our [Discord](https://discord.com/invite/G4PjhEf).

**Comment by NathanPB** [comment]
> Ah well that'll do it haha. Have you considered adding any mechanisms that can make flight more sustainable?

Just adding into @Luligabi1 s comment, we are working on #62 which aims to reduce the cost of basically everything
