### ISSUE TITLE
Server crash with latest version: Exception in server tick loop

### ISSUE THREAD

**Issue by Gamerbolts** [NathanPB/DeepMobLearning-Refabricated#90]
I just downloaded the updated mod for my mod pack and went to go into my world. I right click the Deep Learner and my server crashed. here is the crash report and the latest log. Any help is appreciated :)

[crash-2022-02-22_12.01.12-server.txt](https://github.com/NathanPB/DeepMobLearning-Refabricated/files/8119100/crash-2022-02-22_12.01.12-server.txt)
[latest.log](https://github.com/NathanPB/DeepMobLearning-Refabricated/files/8119101/latest.log)

**Comment by NathanPB** [comment]
Sorry for the inconvenience. Version 0.5.2 fixed this, will be available on curseforge in about 10 minutes

**Comment by Gamerbolts** [comment]
No problem! Thanks for the quick fix
